### ISSUE TITLE
Enhancement: TanStack Table

### ISSUE THREAD

**Issue by jasonwillschiu** [huntabyte/shadcn-svelte#1189]
### Describe the feature

See here
https://github.com/bryanmylee/svelte-headless-table/issues/224

Plus shadcn/ui says it's based on Tanstack Table.

Thanks for all your hard work!
Jason

**Comment by huntabyte** [comment]
The last time I tried tanstack table it was a nightmare. I'll revisit the Svelte 5 rewrite and see how it goes.

**Comment by jessielaf** [comment]
@huntabyte  I have been using tanstack table with Svelte for a while without any problems. Which problems did you encounter?

**Comment by robots4life** [comment]
[https://github.com/TanStack/table/pull/5403](https://github.com/TanStack/table/pull/5403)

**Comment by jasonwillschiu** [comment]
Happy for it to be something that's not TanStack table. Just something that's maintained with similar functionality to ease my mind haha

**Comment by ESchouten** [comment]
Personally I would prefer Tanstack Table, have been using it for over a year and nothing else really comes close to it.

**Comment by shyakadavis** [comment]
I'm indifferent to what ends up being used, but here is something else for consideration. (The runes-powered v2 is currently in preview)

- Repo: https://github.com/vincjo/datatables | Runes - https://github.com/vincjo/datatables/tree/runes
- URL: https://vincjo.fr/datatables.runes/

**Comment by j13n** [comment]
Just tried @tanstack/svelte-table@alpha on one of my current tables since I want to start using Svelte 5. Seems to be working fine.

You do have to have `svelte@next` installed though so for now it looks like:
Svelte 4 with svelte-headless-table and Svelte 5 with @tanstack/svelte-table@alpha.

If @huntabyte and the rest are cool with it I can write some documentation on how to use it. Perhaps a new section on the bottom of the current data-table docs with instructions on how to make data-tables with Svelte 5.

**Comment by robots4life** [comment]
This is just a heads up for anyone following the current docs on Data Table.

I had an [issue](https://github.com/huntabyte/shadcn-svelte/issues/1209) where I wanted to combine pagination and sort with the current Data Table per docs but use a different icon for sorting the table up and down.

The solution is to include 2 unused properties, ` pageCount` and `pageSize`  for the Data Table to work correctly with `props.sort.order`.

```ts
const { hasNextPage, hasPreviousPage, pageIndex, pageCount, pageSize } = pluginStates.page;
```

Even though this is not mentioned in the docs because there an `ArrowUpDown` is used to trigger the sorting it makes sense to want to indicate to the user in what direction the table is currently sorted.

If we stick with svelte-headless-table for a while this is possibly worth mentioning in the docs.

**Comment by stefa168** [comment]
+1 for TanStack

**Comment by huntabyte** [comment]
After having used TanStack pretty extensively over the last few days, I can confirm that most of the issues I experienced with it the first time have been corrected.

If someone would like to update the DataTable docs and examples to use TanStack it would be greatly appreciated, otherwise, I will get to it as soon as I have the chance!

**Comment by c-kirkeby** [comment]
I'll be happy to have a go. I just recently tried to do this myself and I've got a [draft PR open on a personal project](https://github.com/c-kirkeby/osrs-price-site/pull/3). My main blocker has been trying to [pass children to table cells as part of the table definition](https://github.com/TanStack/table/discussions/5705), something that was possible with `svelte-headless-table` but does not seem straightforward with TanStack Table (at least not following their docs).

**Comment by c-kirkeby** [comment]
Okay so rather than doubling up on trying to convert the Tasks demo (@shyakadavis has picked it up in #1260), I implemented the Data Table for my own project here at https://github.com/c-kirkeby/osrs-price-site/pull/3. It doesn't have the filter or the actions / row selection or the filters from the Tasks example, and mine has some more complex use cases like colouring cells / right-aligning cells.

One issue I ran into was this:
https://github.com/c-kirkeby/osrs-price-site/pull/3/files#diff-dfcbcef4795391b3fac61ea52dc73d867264ba430a9ea6dfcab677acd7777e66R72-R73

Due to TanStack/table#4382 there are some TypeScript errors when assigning `columns` to the `ColumnDef<TData, TValue>` type.

**Comment by robots4life** [comment]
It might be worth to point out that TanStack Table will not be supported by Svelte 5 out of the box.

https://github.com/sveltejs/svelte/issues/10359#issue-2111964532

https://github.com/huntabyte/shadcn-svelte/pull/1260#issuecomment-2325916428

Perhaps it is a good idea to wait for TanStack Table to support Svelte 5 before writing new documentation.

**Comment by ESchouten** [comment]
@robots4life Correction: Tanstack Table v8 will not support Svelte 5, Tanstack Table v9 only supports Svelte 5 and up

**Comment by stefa168** [comment]
I have used Tanstack Table v9 alpha and it isn't ready for use yet.

I'd suggest waiting for the release or maybe make separate examples for both Tanstack Table and datatables

**Comment by robots4life** [comment]
Here is a guide to using Svelte 5 with TanStack Table **v8** that @walker-tx put together.

**[https://github.com/walker-tx/svelte5-tanstack-table-examples](https://github.com/walker-tx/svelte5-tanstack-table-examples)**

[https://github.com/TanStack/table/pull/5403#issuecomment-2400783565](https://github.com/TanStack/table/pull/5403#issuecomment-2400783565)

> After some of the questions on Discord and here, I've put together a reference project so folks can see how they can implement their own Svelte 5 adapter for **@tanstack/table-core v8**:

> https://github.com/walker-tx/svelte5-tanstack-table-examples

> Hopefully, this gives folks a clearer path to value.

> Full disclosure: I threw this together in a caffeinated frenzy. Once I get some rest, I'll go back over everything with fresher eyes.

**Comment by huntabyte** [comment]
We're now using TanStack Table in `shadcn-svelte@next` - https://next.shadcn-svelte.com

**Comment by dlamon1** [comment]
Correct me if I'm wrong here, but is the table reactive if it needs to be reassigned ? Is the Tanstack  Svelte lib not using signals ?

**Comment by ESchouten** [comment]
@dlamon1 Tanstack table v9 alpha is

**Comment by itskazemk** [comment]
> The last time I tried tanstack table it was a nightmare. I'll revisit the Svelte 5 rewrite and see how it goes.

now it is the time
