### ISSUE TITLE
Kindly update documentaytion for components as soon as update is released.

### ISSUE THREAD

**Issue by mastmagan007** [huntabyte/shadcn-svelte#131]
### Change Type

Correction

### Proposed Changes

Very first and simple component "Alert", there is nothing named 'Alert' in lib/components/ui
Instead there is lib/components/ui/alert-dialog, and inside there are 5 files but documentation shows only 3.
Almost whole library is full of simple bugs.

**Comment by huntabyte** [comment]
I'm not sure what you're talking about.

There is an [Alert](https://github.com/huntabyte/shadcn-svelte/tree/main/apps/www/src/lib/components/ui/alert) and also an [Alert Dialog](https://github.com/huntabyte/shadcn-svelte/tree/main/apps/www/src/lib/components/ui/alert-dialog).

I'd appreciate it if you'd open an issue for the "simple bugs" so that we can address them!

The project is still in a super early state, once the headless lib is at a stable point a lot of the bugs should go away.
