### ISSUE TITLE
Bugs when running @next CLI

### ISSUE THREAD

**Issue by vrn-hkz** [huntabyte/shadcn-svelte#1530]
### Describe the bug

Running `bunx shadcn-svelte@next init` and `bunx shadcn-svelte@next add button` does not install `bits-ui` as a dependency and int `$lib/components/ui/button/button.svelte`, `import type { WithElementRef } from "bits-ui";` gives an error in the IDE once bits-ui is installed:
![image](https://github.com/user-attachments/assets/2bd4feac-dc19-4e82-a137-2df0fe351791)

It still compiles and runs, and the button works, but wanted to point this out.

### Reproduction

In a brand new `svelte-kit@2.0.0` project run `bunx shadcn-svelte@next init` and `bunx shadcn-svelte@next add button`

### System Info

```bash
System:
    OS: Linux 6.9 Pop!_OS 22.04 LTS
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 15.78 GB / 31.29 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 22.6.0 - ~/.asdf/installs/nodejs/22.6.0/bin/node
    npm: 10.8.2 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 9.1.1 - ~/.local/share/pnpm/pnpm
    bun: 1.1.39 - ~/.bun/bin/bun
  Browsers:
    Chrome: 131.0.6778.85
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.9.0 
    bits-ui: ^0.21.16 => 0.21.16 
    svelte: ^5.0.0 => 5.4.0
```

### Severity

annoyance

**Comment by huntabyte** [comment]
It says your project is still running `bits-ui@0.21.x` when it should be running `bits-ui@next`.

The reason we mention in the CLI that you're using an unsupported runtime is because bun has unpredictable behaviors like this that is inconsistent with other PMs.

We'll look into seeing if we can reproduce and resolve, but in the meantime `bun install bits-ui@next` should do the trick.

**Comment by huntabyte** [comment]
Fixed
