### ISSUE TITLE
Command separator disappears whenever input has value

### ISSUE THREAD

**Issue by mcmxcdev** [huntabyte/shadcn-svelte#1561]
### Describe the bug

I noticed that the separator for the `Command` disappears in my application and was able to reproduce the same problem on https://next.shadcn-svelte.com, see : 

https://github.com/user-attachments/assets/0a5b208d-87e1-4b05-89e4-0033a2986f1a

### Reproduction

Video provided above

### System Info

```bash
-
```

### Severity

annoyance

**Comment by huntabyte** [comment]
This is the same behavior as the original: https://ui.shadcn.com/docs/components/command

![CleanShot 2024-12-19 at 00 01 58@2x](https://github.com/user-attachments/assets/a0f7b743-80cb-4577-a4af-f4fd2459a27d)

https://next.bits-ui.com/docs/components/command#commandseparator

**Comment by mcmxcdev** [comment]
Ah my bad! Seems like I can control it with the `forceMount` prop. Strange that it doesn't always show, seems visually inconsistent to me.

**Comment by huntabyte** [comment]
It's because if you look at the code, the `Separator` doesn't belong to a group or an item; it simply separates them, so there is no way for the separator to know if it should be rendering or not, e.g., when no `Settings` are visible, it wouldn't make sense to render the separator.

Most popular cmdk apps have similar behavior (Raycast, Vercel, etc.).
