### ISSUE TITLE
Ability to use outside of a Sveltekit project

### ISSUE THREAD

**Issue by ramonmalcolm10** [huntabyte/shadcn-svelte#214]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Would it be possible to allow usage outside of a Sveltekit project to supports Svelte project created with Vite or Inertia JS from Laravel. Just a point to note the React version offer this flexibility.

### What type of pull request would this be?

Enhancement

**Comment by huntabyte** [comment]
Is there something preventing it from working now?

**Comment by ramonmalcolm10** [comment]
It make reference to not being able to find something Sveltekit related when you try to install. I will share the exact error in a few

**Comment by huntabyte** [comment]
Ah yes I believe I know what's causing that. I'll look into it and see how feasible it will be to support alternatives!

**Comment by ramonmalcolm10** [comment]
Thanks

**Comment by blcksgnota** [comment]
Any news on this issue? trying to get the package working on a Laravel and svelte project.

**Comment by ramonmalcolm10** [comment]
@huntabyte was wondering if this is the line that is causing the issue [package.json](https://github.com/huntabyte/shadcn-svelte/blob/b1ebb76c846cf2af1829362d4b0f52bd4c8da88d/package.json#L25) and if so can it be executed using the `preinstall` script instead.

Please see [reference](https://github.com/sveltejs/kit/issues/4165#issuecomment-1056767997)  for guidance.

**Comment by sanieldalib** [comment]
+1 on this. Would love to make use of the CLI for a vanilla svelte project without porting over to SvelteKit.

**Comment by huntabyte** [comment]
If anyone has the cycles to dig into this, let me know and it's all yours!

**Comment by willpinha** [comment]
# Why we can't use something other than SvelteKit?

What prevents the CLI from working in projects other than SvelteKit (such as Vite and Laravel) is a specific piece of code.

When we try to run `npx shadcn-svelte@latest init` outside the SvelteKit context, we will probably receive the following error:

```bash
Command failed with exit code 1: npx svelte-kit sync
```

After digging into the code, I realized that the error occurs because of the `resolveConfigPaths` function in [packages/cli/src/utils/get-config.ts](https://github.com/huntabyte/shadcn-svelte/blob/main/packages/cli/src/utils/get-config.ts#L72)

This function attempts to load a TypeScript configuration file at `./svelte-kit/tsconfig.json`. If there isn't, it calls `npx svelte-kit sync` to create it.

As in projects other than SvelteKit we do not have `./svelte-kit/tsconfig.json` nor the `svelte-kit` dependency, the error is thrown.

# The solution

To solve this problem and support other frameworks, we can remove the assumption that `tsconfig.json` is in `./svelte-kit` and instead let the user decide during startup where this file is located.

I'm interested in working on this issue. Can I be assigned to it?

**Comment by willpinha** [comment]
@huntabyte A better way to achieve this, instead of asking for user input, would be to find `tsconfig.json` in a sequence of actions:

1. Search for `tsconfig.json` in cwd
2. If it doesn't exist, search in `./svelte-kit/tsconfig.json`
3. If it doesn't exist, run `npx svelte-kit sync`

Steps 2 and 3 are already implemented. The only thing we would need to add is the first step, so that users outside of a SvelteKit project can also use the CLI

Of course this still assumes that the user is using Typescript in their project, an assumption that shadcn/ui does not make, but I think this can be discussed in another issue

**Comment by 0x090909** [comment]
Would be great! +1 for this feature or bug fix lets say

**Comment by willpinha** [comment]
@0x090909 Sure! I will give it a try

**Comment by lecramr** [comment]
That would be a great addition!
