### ISSUE TITLE
Mistake in Table guide

### ISSUE THREAD

**Issue by philippviereck** [huntabyte/shadcn-svelte#275]
https://github.com/huntabyte/shadcn-svelte/blob/22bd64cf3f03ce2b65984686164d060936700a4d/apps/www/src/content/components/data-table.md?plain=1#L623-L627

```
table.column({
			accessor: ({ id }) => id,
			header: '',
			cell: ({ value }) => {
				return createRender(DataTableActions, { id: value });
			},
			// ...
		})
```

**Comment by huntabyte** [comment]
Yeah, I've actually been meaning to update the data table guide as after I published it I discovered that for the columns that aren't represented by the data, in this case, the select checkbox and the actions, we should be using `table.display` instead of `table.column`.

If anyone wants to update it, feel free to open a PR, otherwise, I will update it when I have some time!

**Comment by philippviereck** [comment]
on it, but I have to admit, it's proving to be more challenging than I initially anticipated! 😅

**Comment by philippviereck** [comment]
I just found: https://github.com/huntabyte/shadcn-svelte/pull/297. Let me know how to continue.
