### ISSUE TITLE
Dashboard demo gets blank when resizing to the narrowest width

### ISSUE THREAD

**Issue by kuatroka** [huntabyte/shadcn-svelte#364]
### Current Behavior

When resizing the shadcn-svelte dashboard demo app to the smallest size, it just turns blank besides the menu bar. See the attached gif.

![shadcn_error](https://github.com/huntabyte/shadcn-svelte/assets/9093546/b91907e5-7e06-46f7-ba31-a8b779305e55)

P.S. I removed the code that shows an image of the dashboard.

### Expected Behavior

It should resize to one column as per the Tailwind CSS classes assigned 

### Steps To Reproduce

run the dashboard demo locally.

**Comment by ollema** [comment]
@kuatroka replacing the actual dashboard with an image is not a bug, but the intentional behaviour no?

see the source code:
https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/lib/components/docs/dashboard/dashboard-page.svelte#L21
https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/lib/components/docs/dashboard/dashboard-page.svelte#L37
```svelte
<div class="md:hidden">
	<img
		src="/examples/dashboard-light.png"
		width={1280}
		height={866}
		alt="Dashboard"
		class="block dark:hidden"
	/>
	...
</div>
<div class="hidden flex-col md:flex">
	...
</div>
```

when the viewport width is small enough, the dashboard will be replaced by a screenshot of the full desktop dashboard instead of showing a more narrow version of the dashboard.

I think the idea is that the full desktop dashboard is a better example of how you could leverage a framework like `shadcn-svelte` (or `shadcn/ui` for that matter).

notice how this behaviour is consistent with https://ui.shadcn.com/examples/dashboard as well!

**Comment by huntabyte** [comment]
As @ollema mentioned, this is expected behavior.

**Comment by kuatroka** [comment]
Sorry, I should have explained it better. The code itself is not a bug as it was indeed intended this way. What I meant by the bug is that when using this code in an actual app (and not as the shadcn-svelte showcase of features) and when removing the image and checking how the app looks on the small screen....then the page goes blank. It doesn't show it badly or "not pretty" - it goes completely blank.

When using it in a real app, one can't just have an image there. I guess what I mean is that the fact that the page goes blank instead of getting the content squeezed is a bug and I can't seem to find a way to show the content even after adding `sm:grid-cols-1` to the top or to the children divs. 

I'm not proper web dev, so I might just be missing something very obvious here.

**Comment by HubbeDev** [comment]
@kuatroka The content is hidden by this line: [Line 37 - Dashboard page component]( https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/lib/components/docs/dashboard/dashboard-page.svelte#L37)

You can change 
```svelte 
<div class="hidden flex-col md:flex">
```
to
```svelte 
<div class="flex-col flex">
```
It's the class 'hidden' that makes it disappear.

**Comment by kuatroka** [comment]
Thanks a lot @HubbeDev ... I think I'll be paying more attention to the `hidden` tags from now on![shad_ok](https://github.com/huntabyte/shadcn-svelte/assets/9093546/239338db-c304-4c09-9e46-c59613f82405)

it's all good now!
