### ISSUE TITLE
Border between rows in table flashes different color for a split second

### ISSUE THREAD

**Issue by AyushSehrawat** [huntabyte/shadcn-svelte#381]
### Current Behavior

Whenever i change the theme to dark/light there is a white border flash for a split second in table component and then it changes to the normal one.

https://www.loom.com/share/5b8f2099222a4b88bdf8e5f9378a4633?sid=efdb20a3-9e38-4427-9ea3-4e912ea464f1

You can also try changing theme on this page and see it

https://www.shadcn-svelte.com/docs/components/data-table

### Expected Behavior

No flash when changing theme

### Steps To Reproduce

1.) Install table component and use it
2.) implement dark/light mode switcher and use it to see

### Link to Reproduction / Stackblitz

https://www.shadcn-svelte.com/docs/components/data-table

**Comment by HubbeDev** [comment]
@AyushSehrawat @huntabyte I think it have to do something with the transition-color class.
If you add transition-none to the table row the flashing is gone. I think their is a bigger problem here tho because that flashing behavor is not only on the table rows. Its on buttons and badges aswell. And probably more. I think it is on every element that have a transition-color on it.

**Comment by huntabyte** [comment]
Thanks for that info @HubbeDev! Was super simple to add into mode-watcher!

**Comment by AyushSehrawat** [comment]
Thanks a lot for fixing @HubbeDev @huntabyte !
