### ISSUE TITLE
Selected value in select component gets lost when closing and reopening accordion

### ISSUE THREAD

**Issue by JustDenP** [huntabyte/shadcn-svelte#436]
### Current Behavior

I wanted to use select components inside an accordion, but a chosen selected value gets lost after closing the component. Other components like inputs, text areas, etc work as expected, and their values persisted.

### Expected Behavior

Saved selected values in a select components

### Steps To Reproduce

<Accordion.Root>
	<Accordion.Item value="item-1">
		<Accordion.Trigger>Is it accessible?</Accordion.Trigger>
		<Accordion.Content>
			<Select.Root>
				<Select.Trigger class="w-[180px]">
					<Select.Value placeholder="Theme" />
				</Select.Trigger>
				<Select.Content>
					<Select.Item value="light">Light</Select.Item>
					<Select.Item value="dark">Dark</Select.Item>
				</Select.Content>
			</Select.Root>
		</Accordion.Content>
	</Accordion.Item>
</Accordion.Root>

import the components, close, and then open it again.

**Comment by huntabyte** [comment]
In this case, since the content is "destroyed" when you close the accordion, what I would do is `bind:selected` to a variable within the component, that way when it is remounted when the accordion is opened, it will have the value populated.

If you can provide me with a minimal reproduction repo/stackblitz, I will demonstrate this for you.
