### ISSUE TITLE
Support for event modifiers

### ISSUE THREAD

**Issue by niemyjski** [huntabyte/shadcn-svelte#462]
### Current Behavior

Currently the following snippet generates an error:  `Event modifiers other than 'once' can only be used on DOM elements svelte(invalid-event-modifier)`

```html
<Button
on:click|preventDefault={() => (toggle= !toggle)}
>
Toggle View
</Button>
```

This is a super common behavior. Perhaps we should add a workaround like this?: https://stackoverflow.com/questions/69630422/svelte-how-to-use-event-modifiers-in-my-own-components

### Expected Behavior

I should be able to use event modifiers

### Steps To Reproduce

1. Define a button
2. Try and use an event modifier.

**Comment by niemyjski** [comment]
This kind of goes along with being able to do other things like actions and `class:tab-active={activeTab === tab}` css binding

**Comment by huntabyte** [comment]
I likely won't action this until after Svelte 5 is released as it's going to change how events are handled entirely.

**Comment by niemyjski** [comment]
@huntabyte Thanks! That's exactly what I did, do you have an example of asChild?

**Comment by huntabyte** [comment]
Im on my phone atm, but I'll try to give an example tomorrow but this should help:

https://www.bits-ui.com/docs/delegation

The specific events that are handled by the library will be typed on the element after the action is applied, and they're all prefixed with 'm-', since they're custom events dispatched from the underlying builders so that prevent default can be used to override the internal behavior on certain components.

In bits I'm basically redispatching those without the prefix to the component to clean it up.

You can read more about how the overriding and such works here:

https://www.melt-ui.com/docs/controlled

In the 'Custom Events' section specifically. Hope this helps!
