### ISSUE TITLE
Add support for astro.

### ISSUE THREAD

**Issue by bloodred17** [huntabyte/shadcn-svelte#485]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I'm facing a lot of issues while trying to use them in Astro.

### What type of pull request would this be?

Enhancement

**Comment by huntabyte** [comment]
Can you elaborate the issues you're having?

**Comment by arjanski** [comment]
I just found this issue as I was researching for Astro support. I have not tried using shadcn-svelte with Astro, but was wondering if there are any general constraints/roadblocks here? I suppose using the CLI to set up a project would obviously not work. 

If using Astro is generally possible, having a small section in the docs explaining the installation and some gotchas would be a great addition IMHO!

Thanks a lot, very happy to see this project evolving.

**Comment by DarthGigi** [comment]
+1 for Astro support

**Comment by samueljoe7** [comment]
Here's how I setup shadcn-svelte with astro by following the vite guide and modifying a few steps. Seems to work well with a few components I tested. Ideally this should work fine for all components, but I currently do not have time to test it. If someone tests this and everything works fine feel free to add the steps to the documentation otherwise, I'll get around to it when I am free.

1. Install tailwind and svelte using astro add
`npx astro add tailwind svelte`
2. Update my tsconfig.json to include lib paths. After this my tsconfig.json looks like this.
```
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "$lib": ["./src/lib"],
      "$lib/*": ["./src/lib/*"]
    }
  }
}
```
3. Disable base styles for tailwind plugin in astro.config.mjs by setting applyBaseStyles to false and adding the following to my astro.config.mjs
```
vite: {
    resolve: {
      alias: {
        $lib: path.resolve("./src/lib")
      }
    }
  }
```
4. The astro.config.mjs file should look something like the below
```
export default defineConfig({
  site: "https://example.com",
  integrations: [tailwind({
    applyBaseStyles: false
  }),  svelte()],
  vite: {
    resolve: {
      alias: {
        $lib: path.resolve("./src/lib")
      }
    }
  }
});
```
5. Create a base.css file under src with the following content
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```
6. Import the base css file in the default layout or page
7. Run `npx shadcn-svelte@latest init`. Use your preferred settings for most of the questions and for the global css point to the base.css file created above(src/base.css)
8. Once the setup is done you can add components from shadcn-svelte. Example using `npx shadcn-svelte@latest add button` will add the shadcn-svelte button component to /src/lib/components and this can be imported to any svelte or astro file by using `import { Button } from "$lib/components/ui/button`

**Comment by gustavomorinaga** [comment]
@arjanski I'm building a small project to study Astro, and also to validate whether it's possible to use the shadcn-svelte components in it. For now I used the Card component as an example, and it worked great! 

I will test other components while developing the application. Maybe I can make step-by-step guide to configure, it's easy at least. 

Take a look at this [repository](https://github.com/gustavomorinaga/codewise/) and [demo](https://codewise-academy.vercel.app/).

**Comment by Lakelimbo** [comment]
Will be fixing this with #1064 👀
