### ISSUE TITLE
In the Form component, please provide information about how the client side can bind to the values being entered in the form fields 

### ISSUE THREAD

**Issue by SumitBando** [huntabyte/shadcn-svelte#491]
### Change Type

Addition

### Proposed Changes

.. in the page https://www.shadcn-svelte.com/docs/components/form

let username
...
<Input name="username" bind:value={username}/>
works, but
<Form.Input name="username" bind:value={username}/>
does not work.

Please also consider redoing the example code to use <Form>
https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/routes/examples/authentication/(components)/user-auth-form.svelte

**Comment by ebrenner-code** [comment]
Yes, this one is driving me crazy, not documented in formsnap or here. With debug=true, we can see the current values of each field, but i have no idea how to access those. Normally we would do it with the $page.form store or a simple bind:value as mentioned, but that seems to not work here.

**Comment by huntabyte** [comment]
You can't bind to them, the `Form.Input` and other components were designed to be a drop in and it works. If you need more control you can checkout the "Controlled Usage" section of the `<Form.Root />` in the [formsnap docs](https://www.formsnap.dev/docs/api-reference/form-root) for now.

We are planning on rewriting Formsnap when we update it to fully support Superforms v2, as after being out in the open for a few months, I've seen what users expect/want v.s. what they don't, which is why I've kept the `Preview` label on it.

Hopefully the second shot at it will be simpler to use for everyone!

**Comment by coryvirok** [comment]
+1 for making accessing form values part of the happy/uncontrolled path. I spent an hour+ trying to figure this out.
