### ISSUE TITLE
Roadmap for Svelte 5 

### ISSUE THREAD

**Issue by stemcc** [huntabyte/shadcn-svelte#493]
### Change Type

Addition

### Proposed Changes

This is actually moreso to start a discussion about Svelte 5 and shadcn-svelte. I know we're still quite a ways out from using runes in production code, and I imagine many libs won't even begin the work to support runes until Svelte 5 has been officially released. 

That said, shadcn and by extension this lib are a little different in how users integrate it into their projects than conventional UI libs. 

Do you mind sharing your plan for Svelte 5 support? If you've got a roadmap, I'm sure there's a few of us who'd love to help you support the transition.

**Comment by huntabyte** [comment]
Fortunately, at this time I have no roadmap. If I did it would have had to change about 10 times since the initial announcement, which is why I haven't been thinking about it and instead have been polishing the underlying libs - bits & melt which will be where most of the heavy lifts for v5 transitions will be.

Once it stabilizes and gets into a release candidate phase I'll start looking into it, but for now, my thoughts are better spent elsewhere!

I will of course update you all once those thoughts do start crossing my mind!

**Comment by oneezy** [comment]
@huntabyte 

![c811c2a1-aaba-4f9f-acc3-44aca173086c_text](https://github.com/huntabyte/shadcn-svelte/assets/7369575/8ba5a93a-6c5b-42b7-aee5-23fe8453d23f)

**Comment by thenbe** [comment]
Whenever you are ready to track progress towards svelte 5 support, can we please re-open this ticket instead of creating a new ticket? This is so that users who have already subscribed to this thread can get notified on updates.

**Comment by OSZII** [comment]
So can we upgrade svelte to version 5 and still use this lib?

**Comment by Bxnq** [comment]
@OSZII 
> So can we upgrade svelte to version 5 and still use this lib?

Since Svelte 5 supports backwards compatibility, you can use the library even if the Svelte version of the package and in your projects are not the same.

**Comment by luxus** [comment]
and there is a active pullrequest
https://github.com/huntabyte/shadcn-svelte/pull/1182
