### ISSUE TITLE
Change default value for optional props from `undefined` to `null`

### ISSUE THREAD

**Issue by DePasqualeOrg** [huntabyte/shadcn-svelte#496]
### Current Behavior

Because of eslint's [no-undef-init](https://eslint.org/docs/latest/rules/no-undef-init) rule, when I open and save the components, or when I run formatting on my repo, the default `undefined` value for optional props in the components gets removed. This rule is part of the popular Airbnb eslint rules. It would be better to set the default to `null` so that it doesn't get removed. When the default value is removed, I get alerts in the console that components were created without required props.

### Expected Behavior

Default value doesn't get removed by eslint

### Steps To Reproduce

Run `npm create svelte@latest my-app`

Add this to .eslintrc.cjs:

```
  rules: {
    'no-undef-init': 'error',
  }
```

Add a prop like this to a component or page:

`export let something: undefined | string = undefined;`

Run `npx eslint . --fix` and see that the default value is removed.

**Comment by huntabyte** [comment]
The problem here is that `undefined` and `null` have completely different meanings in the context of certain props, so this is not something that I will be rewriting the entire library to accommodate.

Maybe with the new way of handling props in svelte 5 the issue will resolve itself but for the time being I'm closing this as not planned.

Airbnbs eslint rules likely don't take framework specific behavior (like props in Svelte) into account.
