### ISSUE TITLE
Use $$restProps.class?

### ISSUE THREAD

**Issue by omar2205** [huntabyte/shadcn-svelte#51]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I see that you're doing this
```ts
export { className as class };
```

To get classes you can use `$$restProps.class`, like so:
```svelte
class={cn("", $$restProps.class)}
```

### What type of pull request would this be?

Enhancement

**Comment by braden-w** [comment]
Notably, the Svelte official docs distinctly mention the `className as class` trick, as you can see [at the end of this section](https://svelte.dev/docs#component-format-script-1-export-creates-a-component-prop):

```html
<script>
let className;

// creates a `class` property, even
// though it is a reserved word
export { className as class };
</script>
```

It also mentions `$$restProps`, but not in the context of `$$restProps.class`. This seems like a tradeoff between less lines and cleanliness/being explicitly with props and I lean towards the `classname as class` method.

**Comment by huntabyte** [comment]
I considered the `$$restProps.class` but ultimately decided on the way it’s implemented due to similar reasons mentioned by @braden-w.

It also leaves the door open for adding types to the components once the Radix types are more stable,  so you’d be able to get type hints for the underlying Radix components if you wanted. 

Most of the Radix types are good to go, but a few (specifically some union types) are still spotty so I’ve refrained from adding `type $$Props = RadixSomethingProps` to anything for the time being.

The awesome thing about owning the components is that you can modify them to fit whatever works best for you! Going to close this issue.

**Comment by omar2205** [comment]
Thanks, @huntabyte.
I was just wondering the reasons made you pick this over restProps.
Have a nice day : )
