### ISSUE TITLE
Header > Row vertical misalignment when enabling sort in 'data-table'

### ISSUE THREAD

**Issue by kuatroka** [huntabyte/shadcn-svelte#521]
### Current Behavior

Reopening as the original shadcn does align the header with the row when sort is enabled.

### Current Behavior

Header > Row vertical misalignment when enabling sort in 'data-table'

**CIK - sort disabled**
![image](https://github.com/huntabyte/shadcn-svelte/assets/9093546/901583b8-818a-4aa9-b0ef-77dd705b4fdf)

**CIK - sort enabled**
![image](https://github.com/huntabyte/shadcn-svelte/assets/9093546/9f00b152-57b9-457b-85fc-a2c8d9133bb8)

### Expected Behavior

It should be aligned as minimum to the left and as maximum to have an option (left or right)

Here is the original shadcn

![image](https://github.com/huntabyte/shadcn-svelte/assets/9093546/2bdf4293-f854-4556-960f-8beea70f56fe)

### Steps To Reproduce

enable/disable `sort` in the `data-table` component

**Comment by kuatroka** [comment]
I checked and the shadcn version of a table where a column doesn't have an icon, is indeed not aligned. 
![image](https://github.com/huntabyte/shadcn-svelte/assets/9093546/5e7114ca-5f36-412c-8e12-8c1bab94b839)

shadcn-svlete only repeats it, so sure please close it if you think it's right. But I think that if the original shadcn does something wrong, maybe shadcn-svelte could improve on it. Thanks

**Comment by ollema** [comment]
> shadcn-svelte only repeats it, so sure please close it if you think it's right. But I think that if the original shadcn does something wrong, maybe shadcn-svelte could improve on it. Thanks

I can't answer for what Hunter thinks, but what I have done in the past when I discovered an issue that was present in both `shadcn/ui` and `shadcn-svelte` is that I opened a ticket for it upstream in `shadcn/ui` and then when it was fixed there it made more sense to also fix here.

see:
https://github.com/shadcn-ui/ui/issues/1627
which I fixed in:
https://github.com/shadcn-ui/ui/pull/1628

and then the same fix was merged in `shadcn-svelte` as well:
https://github.com/huntabyte/shadcn-svelte/pull/326

**Comment by kuatroka** [comment]
Thanks @ollema. You are one of those lucky ones that know both Svelte and React. I don't, so I felt it wouldn't be fair to raise an issue in the original shadcn based only on a screenshot from their docs and not something I can actually check myself. 

In any case, I created the issue [there](https://github.com/shadcn-ui/ui/issues/2079) too

**Comment by ollema** [comment]
> Thanks @ollema. You are one of those lucky ones that know both Svelte and React. I don't, I'm very new to both Svelte and web dev, so I felt it wouldn't be fair to raise an issue in the original shadcn based only on a screenshot from their docs and not something I can actually check myself.
> 
> In any case, I created the issue [there](https://github.com/shadcn-ui/ui/issues/2079) too

I have never written a line of React in my life 😅 the issue I fixed (maybe this issue as well) was simply a CSS/tailwind issue to no knowledge of React was needed.

if you are interested in contributing, I encourage you to give it a shot! you could start with `shadcn-svelte` since you are more familiar with Svelte. download this repo, run for example `pnpm run dev`, find what CSS/tailwind classes might be causing this misalignment.

if you find a fix for `shadcn-svelte` it should be fairly straightforward to port it to `shadcn/ui` since it's probably just a matter of updating a string somewhere.

but if that sounds like a lot of work I understand fully

**Comment by kuatroka** [comment]
Thanks, I'll try to do what you suggest in the 2nd paragraph

**Comment by huntabyte** [comment]
Closing this issue for now. Feel free to reopen if this is addressed in the original.

**Comment by ankyie** [comment]
If  you have used this to make your sorting button:
`header: ({ column }) => {
      return (
        <Button
          variant="ghost"
          onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
        >
          Email
          <ArrowUpDown className="ml-2 h-4 w-4" />
        </Button>
      )
    },`

Then add "className="px-0" to Button, and it fixes it. It was just a padding issue with the button component from Shadcn
Something like this:
`header: ({ column }) => {
      return (
        <Button
          variant="ghost"
          onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          className="px-0"
        >
          Email
          <ArrowUpDown className="ml-2 h-4 w-4" />
        </Button>
      )
    },`
