### ISSUE TITLE
[cli] Pasting a text into the CLI doesn't work

### ISSUE THREAD

**Issue by babakfp** [huntabyte/shadcn-svelte#581]
### Current Behavior

https://github.com/huntabyte/shadcn-svelte/assets/44144724/5301e555-a842-4314-a522-52f67dd9b6c6

I do (`ctrl` + `v`) and it pastes `-` instead of the copied text.

### Expected Behavior

The copied text to get pasted.

**Comment by Skylli202** [comment]
From my test, in local, the issue is that `right-clicking > copy` a file in the explorer tree of VS Code does not copy its filename or path. If you try to paste into a notepad, it is still does not copy anything. In fact, for notepad context menu, your context is empty.


https://github.com/huntabyte/shadcn-svelte/assets/38432216/273ffe79-5171-4115-86ab-6a7694e184f7


That is because what's inserted in the clipboard is not the filename or the path to the file but something else. VS Code is capable of recognizing it because, you can paste into another folder, or paste into a file (which write the filename, but offer you other paste option as well).

**Comment by Skylli202** [comment]
Erratum, the input are handled by [prompts](https://github.com/terkelg/prompts), not commander.

**Comment by AdrianGonz97** [comment]
As @Skylli202 pointed out, your video demonstrated that you were copying by file rather than the filename itself.

**Comment by babakfp** [comment]
It seems like I made a mistake in my demo! Here is a new one:

https://github.com/huntabyte/shadcn-svelte/assets/44144724/ab1bec7e-c976-4dc7-805c-46145650395f

@AdrianGonz97 
@Skylli202

**Comment by AdrianGonz97** [comment]
@babakfp Unfortunately, I'm not able to replicate this: ![img](https://i.imgur.com/fRfm3qY.gif)

Could you provide us with a rundown of your system? 

You can run the following: `npx envinfo --system  --binaries --browsers` and paste the output here.

Here's what I'm using:
```bash
  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 3.12 GB / 31.30 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.volta/tools/image/node/20.9.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.1.0 - ~/.volta/tools/image/node/20.9.0/bin/npm
    pnpm: 8.10.5 - ~/.volta/bin/pnpm
    bun: 1.0.2 - ~/.bun/bin/bun
```
