### ISSUE TITLE
Button & data-sveltekit-preload-data

### ISSUE THREAD

**Issue by jycouet** [huntabyte/shadcn-svelte#60]
### Current Behavior

Today it's not possible to set "data-sveltekit-preload-data" kind of attributes on a Button.

### Expected Behavior

How could it support it?

**Comment by jycouet** [comment]
It's working.
It's just that we don't have auto-complete as VSCode doesn't know "Button" and this attribute.

Maybe you could make it explicit? 
If you feel that it's not the right thing to do, feel free to close the ticket 👍

**Comment by huntabyte** [comment]
The issue I was running into with that was due to the button being able to act as a link OR a button, each of which have their own props. 

Let me look into a union type or possible splitting `<a>` tags into their own component, something I don't _really_ want to do unless it's a dealbreaker for the community.

What are your thoughts on a possible union $$Props type for the button @AdrianGonz97 ?

**Comment by AdrianGonz97** [comment]
> What are your thoughts on a possible union $$Props type for the button @AdrianGonz97 ?

@huntabyte Totally. We can discriminate on the `href` and have something like this:
```ts
type Props = {
    class?: string | null;
    variant?: VariantProps<typeof buttonVariants>["variant"];
    size?: VariantProps<typeof buttonVariants>["size"];
};

interface AnchorElement extends Props, HTMLAnchorAttributes {
    href?: HTMLAnchorAttributes["href"];
    type?: never;
}

interface ButtonElement extends Props, HTMLButtonAttributes {
    type?: HTMLButtonAttributes["type"];
    href?: never;
}

type $$Props = AnchorElement | ButtonElement;
```
Autocomplete for `data-sveltekit-preload-data` and all that fun stuff should work then. It also has the added bonus of yelling at the user if they specify both an `href` and a `type`.
