### ISSUE TITLE
Add shadcn paths to .prettierignore and .eslintignore

### ISSUE THREAD

**Issue by WarningImHack3r** [huntabyte/shadcn-svelte#636]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I think it could be cool to add `aliases.components` and `aliases.utils` to `.prettierignore` and `.eslintignore` at CLI install so they don't get modified by Prettier and ESLint when running the general `prettier --write .` command.

I have no problem with the formatting of my locally installed shadcn components, but it makes them "outdated" from the CLI's perspective. I also don't want to get notified by `prettier --check .` that some of my files are not formatted correctly, which is an opinionated format choice.

I'd understand if I get told it's not the library's responsibility, however, it could be a nice addition because of the uniqueness of shadcn's installation method. What do you think?

### What type of pull request would this be?

New Feature

**Comment by huntabyte** [comment]
Appreciate you taking the time to make this request!

I get where you're coming from, however, I think having this as a default rather than peeps adding it themselves would be _unexpected_ behavior, considering the idea of you owning the code. Additionally, this would introduce more complexity into the CLi before we even add things that will warrant the complexity (non-TS, CSS vars, etc.). We wouldn't be able to assume everyone is using eslint and prettier, so more checks would need to go in place, and then the topic of monorepos comes into the mix which makes things even more of a PITA.

So for now, I'm going to say this isn't going to be on the lib's area of responsibility, however, if this request comes up more frequently, it could be something we consider later down the line.

I'd like to improve the `diff` ability, which could involve some temp formatting so it doesn't matter what we/you use for your prettier config, but this is down the road on the roadmap!

**Comment by WarningImHack3r** [comment]
Thanks for this detailed answer! I completely understand your point and I'm not surprised by your statement.

It's true that a diffing mechanism would be an even better solution, I'm stealing that idea to make it feature of my recently released [shadcn IntelliJ extension](https://github.com/WarningImHack3r/intellij-shadcn-plugin)!
