### ISSUE TITLE
bug: Lucide icons overlap the `Alert` component on Firefox

### ISSUE THREAD

**Issue by AdrianGonz97** [huntabyte/shadcn-svelte#7]
![ff](https://i.imgur.com/KHWVVDp.png)

**Comment by huntabyte** [comment]
Is this something we feel we should accommodate Firefox for? The `has` selector is what makes this component so simple to use. I'd be open to it if there was an alternative way with comparable implementation.

**Comment by Mxrk** [comment]
> Is this something we feel we should accommodate Firefox for? The `has` selector is what makes this component so simple to use. I'd be open to it if there was an alternative way with comparable implementation.

I probably wouldn’t make a change here because of your reasoning. 
But, I found a package on npm which could solve that problem till Firefox gets support (didn’t test it yet). Maybe, if it works, add a note in the documentation that this could solve the problem with Firefox? And then just remove the note again when the update dropped.

https://www.npmjs.com/package/css-has-pseudo

**Comment by huntabyte** [comment]
Closing as not implementing
