### ISSUE TITLE
[Critical]while init command, Package manager Errors out, assumes bun as default, despite setting alias bun=pnpm

### ISSUE THREAD

**Issue by nikhil-swamix** [huntabyte/shadcn-svelte#828]
### Describe the bug

![image](https://github.com/huntabyte/shadcn-svelte/assets/54004431/d2288e14-ce65-484b-9cc9-cc4e9beb2385)
unless i add 
	"packageManager": "pnpm@8.7.6",
it always defaults to bun, and the above images show.
beginner will have lot of trouble.
fix is in the get-package-manager file in utils folder of source code, and check presence of lock file using regex instead of some crazy thirdparty lib. "bunlock" "pnpmlock" etc...
______
Should i attempt fix by opening PR? trust me i have linux distro level maintainer skill, JK, i just want to make exp seamless, good lib and concept though.

### Reproduction

running on windows, previously project was setup with pnpm, slowly tried to add shadcn-svelte, but met with deadly errors.

### System Info

```bash
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 6.78 GB / 15.94 GB
  Binaries:
    Node: 20.6.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.6 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.52)
  npmPackages:
    @sveltejs/kit: ^2.0.6 => 2.0.6
    svelte: ^4.2.8 => 4.2.8
```

### Severity

blocking all usage of shadcn-svelte

**Comment by AdrianGonz97** [comment]
> fix is in the get-package-manager file in utils folder of source code, and check presence of lock file using regex instead of some crazy thirdparty lib. "bunlock" "pnpmlock" etc...

`@antfu/ni` detects the package manager through 2 methods:
1. It first checks the `packageManager` field in the project's `package.json`
1. If the above is missing, it will then try to determine the PM based on the lockfile found in the project

If both of those are fail, our CLI will then try to determine the PM based on the user agent that's provided by the PM. If that fails as well, we fallback to using `npm`.

---

With all of that said, is there a `bun.lockb` file already present in your project? If that's the case, then that would explain why it's trying to use `bun` instead of `pnpm`.

If that's not the case, then it would be useful if you could also provide a reproduction of the project that you're running the `pnpm dlx shadcn@latest init` command on.

**Comment by nikhil-swamix** [comment]
@AdrianGonz97 ahhh, indeed, that was a good catch, i was having double thoughts since it worked well in empty repo. issue was with presence of bun.lockb existence. close the issue, thanks.
