### ISSUE TITLE
CLI  doesn't verify bits-ui dependency is correct for scroll-area

### ISSUE THREAD

**Issue by Masstronaut** [huntabyte/shadcn-svelte#895]
### Describe the bug

the CLI doesn't insure that a sufficiently recent version of "bits-ui" is installed to support the `scroll-area` component.

### Reproduction

1. Have bits-ui version set to "^0.18.6"
2. Run `npx shadcn-svelte@latest add scroll-area` (note that it *should* require bits-ui 0.19.0)
3. Open the installed `scroll-area.svelte` component
4. Observe that bits-ui doesn't export ScrollArea

<img width="564" alt="image" src="https://github.com/huntabyte/shadcn-svelte/assets/9017393/38f25755-f900-4518-948a-eee6ca85c88b">

### System Info

```bash
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 193.03 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - /opt/homebrew/bin/node
    npm: 10.4.0 - /opt/homebrew/bin/npm
    pnpm: 8.12.1 - ~/Library/pnpm/pnpm
  Browsers:
    Safari: 17.2.1
  npmPackages:
    @sveltejs/kit: ^2.0.6 => 2.4.3
    bits-ui: ^0.18.6 => 0.18.6
    formsnap: ^0.5.1 => 0.5.1
    svelte: ^4.2.12 => 4.2.12
    sveltekit-superforms: ^2.8.0 => 2.8.0
```

### Severity

annoyance

**Comment by huntabyte** [comment]
We don't forcefully update the package or keep track of versions that each component depends on, otherwise, we'd have to basically maintain our own npm which we aren't willing to do at the moment. This is something we'll be able to do once bits is at a stable release but right now it could possibly introduce unexpected breaking changes to other components by simply adding a new one.

**Comment by Masstronaut** [comment]
Is it reasonable to at least add a warning in the CLI? I think there is a divergence from expectations when the CLI says it is installing dependencies, but does not in fact install/update to the required dependencies.
