### ISSUE TITLE
Putting dialog trigger inside dropdown menu adds an extra div

### ISSUE THREAD

**Issue by ChrisPoul** [huntabyte/shadcn-svelte#902]
### Describe the bug

I wan't to use a dialog and put it's trigger inside a dropdown menu, the issue I'm having is that it messes up the look since it adds an extra div that wasn't there before.

Here's how it looks when not using the dropdown component:
![image](https://github.com/huntabyte/shadcn-svelte/assets/68830860/378c6db4-11a1-4a2c-9d5e-b6967e5887b0)

It behaves as expected with no problem, but when I instead try to use the dropdown menu this happens:
![image](https://github.com/huntabyte/shadcn-svelte/assets/68830860/6b225640-85ff-4c18-b479-39cfbe27d91b)

Now there is sudenly an extra div right after the trigger button and this messes up the look of the links.

Here's the code of the dropdown menu:

```svelte
<script lang="ts">
	import NavLinks from './NavLinks.svelte';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as DropdownMenu from '$lib/components/ui/dropdown-menu/index.js';
</script>

<DropdownMenu.Root>
	<DropdownMenu.Trigger asChild let:builder>
		<Button builders={[builder]} variant="outline">Open</Button>
	</DropdownMenu.Trigger>
	<DropdownMenu.Content
		class="p-6 2xs:px-10 text-center flex flex-col gap-4 bg-black bg-opacity-90"
	>
		<NavLinks />
	</DropdownMenu.Content>
</DropdownMenu.Root>

```

And this is is the code in the NavLinks component:

```svelte
<a class="link" href="/#nosotros" rel="ugc"> Nosotros </a>
<a class="link" href="/#servicios" rel="ugc"> Servicios </a>
<a class="link" href="/soporte" target="_blank" rel="ugc"> Soporte </a>
<a class="link" href="/#clientes" rel="ugc"> Clientes </a>
<Contact>
	<button class="link">Contacto</button>
</Contact>
<a class="link" href="/tienda" rel="ugc"> Tienda en Línea</a>

<style lang="postcss">
	.link {
		@apply font-medium text-black hover:text-gray-700
		dark:text-white dark:hover:text-zinc-300 hover:scale-105;
	}
</style>
```

It's just a couple of a tags, I need to do it this way because I use those tags somewhere else with a different format.

### Reproduction

You can just copy and paste the code I provided in the description

### System Info

```bash
System:
    OS: Linux 5.15 openSUSE Tumbleweed 20240305
    CPU: (12) x64 AMD Ryzen 5 Microsoft Surface (R) Edition
    Memory: 3.73 GB / 7.49 GB
    Container: Yes
    Shell: 3.6.0 - /usr/bin/fish
  Binaries:
    Node: 21.7.1 - ~/.local/share/nvm/v21.7.1/bin/node
    Yarn: 1.22.19 - /mnt/c/Users/Chris/AppData/Roaming/npm/yarn
    npm: 10.5.0 - ~/.local/share/nvm/v21.7.1/bin/npm
    pnpm: 8.15.4 - ~/.local/share/pnpm/pnpm
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.2
    bits-ui: ^0.19.5 => 0.19.5
    svelte: ^4.2.7 => 4.2.12
```

### Severity

annoyance

**Comment by gregmsanderson** [comment]
Hi @ChrisPoul 

I also ran into a problem when calling a Dialog from within a Dropdown menu. It's mentioned a lot on the original Shadcn repo (the ui.shadcn.com) and people suggest different ideas over there that you can probably translate here. This uses the same basic ideas after all.

It sounds like your issue may be solved by what I did: open the Dialog _programatically_ using a standard Dropdown.Item element. That way the Dialog is not "in" the Dropdown menu. It's a _sibling_ of it. So it won't add any div etc. which may be breaking your layout.

The idea is essentially this (in my case, it's an AlertDialog rather than a Dialog, but the same idea applies).

```
<DropdownMenu.Root>
	<DropdownMenu.Trigger asChild let:builder>
		<Button variant="ghost" builders={[builder]} class="relative h-8 w-8 p-0">
			<span class="sr-only">Open menu</span>
			<Icons.DotsHorizontal class="h-4 w-4" />
		</Button>
	</DropdownMenu.Trigger>
	<DropdownMenu.Content>
		<DropdownMenu.Item href="/example">Example</DropdownMenu.Item>
		<DropdownMenu.Item on:click={openDialog(exampleParam)}>Open dialog</DropdownMenu.Item>
	</DropdownMenu.Content>
</DropdownMenu.Root>
```

Notice that rather than have a Dialog with a Trigger component, there is an `on:click` instead. _Now_ the Dialog does not need a Trigger component. So you can put the Dialog as a sibling, below it, and so _its_ HTML can't affect the Dropdown HTML e.g

```
<AlertDialog.Root open={dialogOpen} onOpenChange={(open) => (dialogOpen = open)}>
	<AlertDialog.Content>
		<AlertDialog.Header>
			<AlertDialog.Title>Example</AlertDialog.Title>
			<AlertDialog.Description>Are you sure?</AlertDialog.Description>
		</AlertDialog.Header>
		<AlertDialog.Footer>
			<AlertDialog.Cancel>No</AlertDialog.Cancel>
		</AlertDialog.Footer>
	</AlertDialog.Content>
</AlertDialog.Root>
```

Note that since the Dialog is now being opened with an `on:click` you will need to keep track of its opened state with a boolean. Why? Well ... if someone _opens_ the Dialog with a click on the Dropdown ... but then _closes_ it by pressing Escape ... your UI is then out of sync. Hence the `dialogOpen` which is set as true within `dialogOpen(...)`.

**Comment by ChrisPoul** [comment]
Thank you for your help @gregmsanderson, this solved my issue

**Comment by Stadly** [comment]
Very helpful, @gregmsanderson!

I _think_ you could do `<AlertDialog.Root bind:open={dialogOpen}>` and let the two-way binding take care of keeping `dialogOpen` in sync :)

**Comment by gregmsanderson** [comment]
@Stadly No problem. You may well be right about that.
